import { getNearbyEnemyTokens } from "./enemies.mjs";

/**
 * Nemesis Drain (Finster's Monster-Matic Cookbook, all 6 Psycho Paths, 7th level, p.284 etc.):
 * "Once per scene, spend 2 Personal Power as a Standard action to make a single Intimidation
 * Skill Test against the Willpower Defense of every Power Ranger within 30 feet. Each target
 * successfully hit loses 1 Personal Power and takes a -1 penalty to any Defenses that gained a
 * bonus from armor generated by the It's Morphin Time! Role Perk, until the end of the scene."
 *
 * Same Absolute-Menace-style AoE shape (helpers/absolute-menace.mjs's own doc comment) - auto-
 * target every enemy within range via canvas.tokens.setTargets(), then trigger the actual roll via
 * actor._dice.rollSkill() with a synthetic dataset. The Power spend and once-per-scene gate are
 * handled by the banked-buffs.mjs dispatch, same split as Elemental Storm's own identical shape.
 *
 * The Defense penalty is approximated as -1 to BOTH Toughness and Evasion while the target is
 * Morphed - It's Morphin Time! is this system's own generic "+2 deflective bonus" grant most PR
 * actors' own Morphed Toughness/Evasion ultimately trace back to (the same `hasMorphedToughnessBonus`
 * flag referenced elsewhere in this project), and this codebase has no per-source Defense-bonus
 * provenance tracking to identify "just the bonus that came from armor" more precisely than that.
 * Read live (not consumed) in dice.mjs's own per-target checkEntries construction, the same shape
 * Monster Morph/Grow's own Defense bonuses already established - never written to
 * system.defenses.<type>.bonus. "Until the end of the scene" has no active expiry, the same
 * unenforced-duration idiom used throughout this project.
 */
const RADIUS_FEET = 30;
const NEMESIS_DRAIN_PENALTY_FLAG = 'nemesisDrainPenaltyActive';

/**
 * Targets every enemy within 30ft and kicks off the Intimidation-vs-Willpower Skill Test. The
 * Power spend and once-per-scene marking happen in banked-buffs.mjs, before this is ever called.
 * @param {Actor} actor
 */
export async function activateNemesisDrain(actor) {
  const enemies = getNearbyEnemyTokens(actor, RADIUS_FEET);
  canvas.tokens.setTargets(enemies.map(token => token.id));

  await actor._dice.rollSkill({
    skill: 'intimidation',
    essence: 'social',
    shiftUp: 0,
    shiftDown: 0,
    defenseType: 'willpower',
    isNemesisDrain: true,
  }, actor);
}

/**
 * Docks 1 Personal Power (floored at 0, a no-op if the target has no Personal Power pool at all)
 * and marks the target's own Toughness/Evasion penalty active.
 * @param {Actor} targetActor
 */
export async function applyNemesisDrainEffect(targetActor) {
  if (targetActor.system.powers?.personal) {
    await targetActor.update({
      'system.powers.personal.value': Math.max(0, targetActor.system.powers.personal.value - 1),
    });
  }

  await targetActor.setFlag('essence20', NEMESIS_DRAIN_PENALTY_FLAG, true);
}

/**
 * The live, non-consumed Defense penalty from a prior Nemesis Drain hit - see this file's own doc
 * comment for why it's read here rather than written into system.defenses.<type>.bonus.
 * @param {Actor} targetActor
 * @returns {Number}   0 or -1.
 */
export function getNemesisDrainPenalty(targetActor) {
  if (!targetActor?.system?.isMorphed || !targetActor.getFlag?.('essence20', NEMESIS_DRAIN_PENALTY_FLAG)) {
    return 0;
  }

  return -1;
}
